name: Jakarta_labb CI pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 20 # Outdated JDK version to support WildFly
        uses: actions/setup-java@v4
        with:
          java-version: '20' # Outdated JDK version to support WildFly
          distribution: 'temurin'
          cache: maven
      - name: Test
        run: mvn -B test --no-transfer-progress
      - name: Cleanup merged branches
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: |
          git fetch --prune
          git push origin --delete "${{ github.event.pull_request.head.ref }}"