name: Jakarta_labb CI pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 20 # Outdated JDK version to support WildFly
        uses: actions/setup-java@v4
        with:
          java-version: '20' # Outdated JDK version to support WildFly
          distribution: 'temurin'
          cache: maven
      - name: Test
        run: mvn -B test --no-transfer-progress
      - name: Cleanup merged branches
        run: |
          git fetch --prune
          for branch in $(git branch --merged | grep -v "main"); do
            git push origin --delete "$branch"
          done